CI test

diff --git a/.github/workflows/.code-linting.yml b/.github/workflows/.code-linting.yml
--- a/.github/workflows/.code-linting.yml
+++ b/.github/workflows/.code-linting.yml
@@ -24,7 +24,7 @@ jobs:
         version: [14, 15, 16]
     timeout-minutes: 60
     steps:
-      - name: "Install required packages"
+      - name: "Install required system packages"
         run: >
           apt update &&
           DEBIAN_FRONTEND=noninteractive apt install -y 
@@ -44,6 +44,99 @@ jobs:
         uses: ./.github/actions/checkout-ns3
       - name: "Check code style"
         run: python3 utils/check-style-clang-format.py --verbose .
+
+  test-workspace:
+    runs-on: ubuntu-latest
+    container:
+      image: ubuntu:rolling
+    steps:
+      - run: mkdir -p src/lorawan
+      - run: echo $GITHUB_WORKSPACE
+        working-directory: ./src/lorawan
+
+  # Clang-tidy
+  clang-tidy-16:
+    if: ! always()
+    runs-on: ubuntu-latest
+    container:
+      image: ubuntu:rolling
+    timeout-minutes: 180
+    continue-on-error: true
+    env:
+      MPI_CI: 1
+      CLANG_TIDY_OUTPUT: clang-tidy-output.log
+      FILES_CHANGED: git-diff-name-only.log
+    steps:
+      - name: "Install required system packages"
+        run: >
+          apt update &&
+          DEBIAN_FRONTEND=noninteractive apt install -y
+          clang cmake
+          clang-tidy clang-tidy-16
+          python3 python3-pip
+          libboost-all-dev libeigen3-dev libgtk-3-dev libopenmpi-dev libsqlite3-dev
+          gsl-bin libgsl-dev libgsl27
+          git ssh
+      - name: "Install required python packages"
+        run: pip3 install --break-system-packages cppyy
+      # The following 2 steps are required...
+      # Github workflows/actions are too limited >:(
+      # They will be duplicated in all reusable workflows
+      - name: "Retrieve action from repository"
+        uses: actions/checkout@v4
+        with:
+          sparse-checkout: |
+            .github/actions/checkout-ns3
+          sparse-checkout-cone-mode: false
+      - name: "Checkout this repository as ns-3 module"
+        uses: ./.github/actions/checkout-ns3
+      - name: "Configure ns-3 CMake"
+        run: >
+          ./ns3 configure -d debug
+          --enable-clang-tidy
+          --enable-examples --enable-tests --enable-asserts
+          --enable-mpi --enable-python-bindings
+      - name: "Get list of changed files"
+        working-directory: ./src/lorawan
+        run: >
+          if (git remote | grep -qw upstream) ; then
+          git remote remove upstream ;
+          fi &&
+          git remote add -t master --no-tags -f upstream https://github.com/signetlabdei/lorawan.git &&
+          git diff --name-only upstream/master > ../../$FILES_CHANGED
+      # Run clang-tidy-diff in the opposite cases of the if-else below.
+      # File paths generated by git diff are relative to the working tree. Therefore, iregex should only contain paths relative to the working tree.
+      - name: "Running clang-tidy-diff"
+        working-directory: ./src/lorawan
+        run: >
+          if !([[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]] || (grep -q ".clang-tidy" $FILES_CHANGED)) ; then
+          echo "Running clang-tidy-diff" ;
+          git diff -U0 upstream/$CI_DEFAULT_BRANCH |
+          clang-tidy-diff-16.py -path cmake-cache/ -p1 -quiet -use-color
+          -iregex "(contrib|examples|src|scratch|utils)\/.+\.(cpp|cc|cxx|c|h|hpp)"
+          1> $CLANG_TIDY_OUTPUT
+          2> /dev/null ;
+          fi
+      # Run full clang-tidy in the following cases: 1) default branch, 2) ".clang-tidy" file changed, 3) clang-tidy-diff had an error
+      - name: "Running full clang-tidy"
+        working-directory: ./src/lorawan
+        run: >
+          if [[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]] || (grep -q ".clang-tidy" $FILES_CHANGED) || (egrep -q -A 3 "file not found \[clang-diagnostic-error\]" $CLANG_TIDY_OUTPUT) ; then
+          echo "Running full clang-tidy" ;
+          run-clang-tidy-16 -p cmake-cache/ -quiet
+          1> $CLANG_TIDY_OUTPUT
+          2> /dev/null ;
+          fi
+      - name: "Check job results"
+        run: >
+          (! egrep -A 3 "error:|warning:|note:" $CLANG_TIDY_OUTPUT)
+          echo "No clang-tidy errors found"
+      - name: "Upload build artifacts"
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ CLANG_TIDY_OUTPUT }}
+          path: ${{ CLANG_TIDY_OUTPUT }}
 
   # Emacs line
   emacs-line:
